### PR TITLE
Comms 9

### LINKED ISSUE #35: Comms Issue #9
Page errors : 

The stylesheet https://wet-boew.github.io/themes-dist/GCWeb/assets/favicon.ico was not loaded because its MIME type, “image/vnd.microsoft.icon”, is not “text/css”. alouette

downloadable font: Failed to convert WOFF 2.0 font to SFNT (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:1) source: https://wet-boew.github.io/themes-dist/GCWeb/fonts/glyphicons-halflings-regular.woff2 

downloadable font: rejected by sanitizer (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:1) source: https://wet-boew.github.io/themes-dist/GCWeb/fonts/glyphicons-halflings-regular.woff2 

SecurityError: The operation is insecure. 39dcce94-3ae2-44a0-b0a0-34b18ac05b1c:1

downloadable font: Failed to convert WOFF 2.0 font to SFNT (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:1) source: https://wet-boew.github.io/themes-dist/GCWeb/fonts/glyphicons-halflings-regular.woff2 

downloadable font: rejected by sanitizer (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:1) source: https://wet-boew.github.io/themes-dist/GCWeb/fonts/glyphicons-halflings-regular.woff2

http://13.88.240.170:8888/alouette/

### PR DESCRIPTION
**Pull request by coleweusthem**
should resolve #35

### CODE REVIEW

**Comment by nfee006** [comment]
@coleweusthem: if I understand correctly, some/most resources (js etc...) are still pointing to https://wet-boew.github.io/themes-dist/GCWeb. Would it be possible to store those locally?

**Comment by coleweusthem** [comment]
@nfee006, I was following the suggestions of the contact you had for the theme. I suppose we could try storing them locally though, but let's wait on an answer to the iframe idea we had in the meeting.

**Comment by nfee006** [comment]
Ok, sounds good. Would caution against making changes to the existing header/footer at all since it's going to have to be 100% scrapped either way.

Not sure what you did here specifically to solve #35 but I'm not able to replicate the errors so it must be fixed? I am also unable to replicate on an older instance but that's likely because of broken links.

**Review by nfee006 — APPROVED** [review]
Unable to replicate error. Approved with the understanding that we may need to revisit this once we address the header/footer/theming issue more comprehensively.

**Pull request merged**
