### PR TITLE
Theme fix

### PR DESCRIPTION
**Pull request by coleweusthem**
@nfee006 this should make the theme appear as it did before the asset sources were removed

### CODE REVIEW

**Comment by nfee006** [comment]
Thanks @coleweusthem, I'll have a look.

**Comment by nfee006** [comment]
@coleweusthem the dropdown menu formatting is still broken. Would it be possible to address this please? 

image

**Comment by nfee006** [comment]
@coleweusthem pretty sure this is the issue. Do you mind if I add the fix to your pull request/branch for Alouette +SCISAT? 
image

**Comment by nfee006** [comment]
Works well, thanks @coleweusthem

**Comment by coleweusthem** [comment]
@nfee006 the only issue I see with that fix is it's not responsive, but doing some testing with a fix value I see the page isn't very responsive anyways. So that should work.

**Comment by nfee006** [comment]
Agreed - not as a responsive as it could be. Feel free to change it if needed for conformity. I needed a short-term fix to make production usable again. Thanks.

**Comment by coleweusthem** [comment]
@nfee006 and a question on the compiled.css file, is it being compiled somewhere or is that simply the name? I was avoiding it under the assumption that it may be an auto compiled file where changes may be overwritten.

**Comment by nfee006** [comment]
I'm reasonably certain that that's just the name but I'll ask around. It doesn't seem to be well documented.

**Pull request merged**
