### PR TITLE
Comms 3

### PR DESCRIPTION
**Pull request by coleweusthem**
should resolve #comms issue #29

### CODE REVIEW

**Review by nfee006 — COMMENTED** [review]
Approved for scisat/

**Review by nfee006 — APPROVED** [review]

**Review by nfee006 — CHANGES_REQUESTED** [review]
Sorry, double-checked. Still seems to have the issue - am I missing something?
image

**Comment by coleweusthem** [comment]
@nfee006, my mistake, I misread and fixed the x on the select field not the drop down

**Comment by coleweusthem** [comment]
@nfee006 should we move the fields above the graph just so they have more room, theres not much we can do in the space we have to fix this issue.

**Comment by nfee006** [comment]
Is there a way of setting a minimum size for them so that that doesn't happen? If the only way to fix is to pull the dropdowns above (but within the same box) then go for it.

**Comment by coleweusthem** [comment]
@nfee006 I'm going to move them above. To make them smaller would cut off text which doesn't seem like a good option.

**Comment by nfee006** [comment]
I meant minimum size of the box they're in but that's fine - as long as there aren't any accessibility considerations (and there shouldn't be).

**Comment by coleweusthem** [comment]
@nfee006, take a look, I like how it ended up giving more room for the graphs as well.

**Comment by nfee006** [comment]
I like the format itself - the dropdowns are huge though. Is that something worth addressing in your opinion? Might look weird if they're too small as well.

**Comment by nfee006** [comment]
Context: 
image

**Comment by coleweusthem** [comment]
@nfee006, thats fair I had my window a lot smaller. Put them side by side maybe? and a max-width for good measure?

**Comment by nfee006** [comment]
Yeah I like that (again, assuming no impacts on accessibility/keyboard navigation).

**Comment by coleweusthem** [comment]
@nfee006, that should do it

**Comment by nfee006** [comment]
Looks good! I wasn't sure about the left-justified buttons but it's growing on me. Approved. 

image

**Review by nfee006 — APPROVED** [review]

**Pull request merged**
