### PR TITLE
Full implementation of text tables

### PR DESCRIPTION
**Pull request by dreneuw**
Full implementation of text tables for all 4 graphs, including translations

### CODE REVIEW

**Comment by dreneuw** [comment]
I seem to have translation issues at this stage in the branch, but that is probably an App-Launcher problem.

In addition, I am getting issues with some of the tables, specifically with the page navigation: the old page navigation is showing
image
I implemented the work Cole had done in Scisat into Alouette so there is a chance I missed something. Could you please check it out @coleweusthem ? Thanks!

Other than these issues, the tables seem fully implemented, once these two issues are confirmed fix we should be able to merge.

**Comment by nfee006** [comment]
Checking.

**Review by nfee006 — CHANGES_REQUESTED** [review]
Looks good overall. Are you sure that this is up to date with development (not the PR that I just merged but before that)? There seem to be some older things in there "Search Canadian Space Agency" in the header search field for example. The merge conflicts will also need to be addressed. 
 
1. Capitalization
image
2. This pagination needs to be removed. 
image
3. Ideally the pagination should be centered like it is with SCISAT. Also, it still seems to be using the term "Goto" in the aria-labels - @coleweusthem?
4. We'll need to check that it translates properly with the most recent PR bugfix. It's not translating right now but nothing is.

**Review by nfee006 — APPROVED** [review]
Approved

@coleweusthem - we'll need your help with these two things at one point though. Not clear how they should be ported over. 

image

**Comment by coleweusthem** [comment]
I had to use a CSS rule to hide the pagination, and Goto is kind of the standard way to label pagination elements. If you want to use something else let me know what that is.

**Comment by nfee006** [comment]
If Goto is standard just keep it. Would be good to have that css rule written down in the documentation somewhere at one point. Thanks Cole.

**Pull request merged**
