### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by coleweusthem**
more fixes and validator fixes

### CODE REVIEW

**Comment by nfee006** [comment]
@coleweusthem 

Still seeing that issue with the breadcrumb

**Comment by nfee006** [comment]
https://github.com/asc-csa/AlouetteApp/issues/108

**Comment by nfee006** [comment]
Formatting is looking good. We had discussed linking the top error list to the fields - any luck with that? 
image
image

**Comment by coleweusthem** [comment]
@nfee006, I'm going to get scisat working again first. Not sure whats going on with it yet.

**Comment by nfee006** [comment]
Working again? Feel free to tag/email me if you need an extra set of eyes.

**Comment by coleweusthem** [comment]
@nfee006, not quite sure where it stopped displaying the summary thing above all the fields, but I'm tracking down whats causing it

**Review by nfee006 — CHANGES_REQUESTED** [review]
"You are here" must be translated on the French page.

Work that could be included in a future pull request: linking the top list of errors to the relevant fields.

**Comment by coleweusthem** [comment]
@nfee006, you should be able to, I'm just going through the issues I had opened and checking they're done

**Comment by nfee006** [comment]
Approved for breadcrumb change.

Could've sworn I had already submitted this but I don't see it. The validator looks great except 1 thing: it's only listing one error in the list at the top. Any ideas?

**Comment by nfee006** [comment]
@coleweusthem Also I just noticed that you're trying to merge to master.

**Comment by coleweusthem** [comment]
@nfee006, you're right. Lets just keep this going for now. We'll close it and merge to master once everything is done

**Comment by coleweusthem** [comment]
@nfee006, that should resolve that.

**Comment by nfee006** [comment]
Approved for form validation. Great work!

image
image

**Review by nfee006 — APPROVED** [review]

**Comment by nfee006** [comment]
@coleweusthem Are we ok to merge on your end or is there anything else?

**Comment by nfee006** [comment]
@coleweusthem can we close this?

**Comment by coleweusthem** [comment]
@nfee006, I believe we can close this. If memory serves we created a new pull request to merge to development instead on friday

**Pull request closed without merging**
