### PR TITLE
urlencoded the issue link

### PR DESCRIPTION
**Pull request by coleweusthem**
#45 should be resolved now

### CODE REVIEW

**Comment by nfee006** [comment]
Still causing the error to appear on my side for both download buttons - how about on yours?

image

**Comment by coleweusthem** [comment]
@nfee006, sorry missed the second I'll have it corrected shortly.

**Comment by coleweusthem** [comment]
@nfee006, added it for the second link

**Comment by nfee006** [comment]
Approved for comms issue 19 (#45)

**Pull request merged**
