### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by coleweusthem**
merging to the correct branch this time

### CODE REVIEW

**Comment by nfee006** [comment]
Approved for https://github.com/asc-csa/AlouetteApp/pull/99. 

I believe that we still need something for https://github.com/asc-csa/AlouetteApp/pull/101 before merging this one, right? Or am I able to merge and https://github.com/asc-csa/AlouetteApp/issues/103 can be another pull request? I'd like to have a master version that's compatible with the new App-Launcher so that I can test on @ data at some point.

**Comment by coleweusthem** [comment]
@nfee006 they should all be good to merge now

**Comment by nfee006** [comment]
Ok, great. Just as long as #103 is still on your radar.

**Comment by coleweusthem** [comment]
@nfee006, I'm going to upload the newest version of dash core components here. You might run into an issue without it

**Comment by coleweusthem** [comment]
[dash_core_components.tar.gz](https://github.com/asc-csa/AlouetteApp/files/6379621/dash_core_components.tar.gz)

**Review by nfee006 — APPROVED** [review]

**Pull request merged**
