### PR TITLE
Comms issue 32

### PR DESCRIPTION
**Pull request by coleweusthem**
I believe this addresses what was asked in issue #57

### CODE REVIEW

**Comment by coleweusthem** [comment]
@nfee006, I believe this addresses what they were asking for in issue 32

**Comment by nfee006** [comment]
I'll have a look in the morning, thanks @coleweusthem

**Comment by nfee006** [comment]
I'll need to get back to you on this one.

**Comment by coleweusthem** [comment]
@nfee006 I'll actually need to change this, accidentally requested merge to master

**Comment by coleweusthem** [comment]
Oh, this was actually included as part of another pull request. If it looks acceptable we can close the issues it covered

**Comment by nfee006** [comment]
I'll let you know - I need to get clarifications from comms.

**Comment by nfee006** [comment]
I reread their original comments and agree that this seems to address their concerns. Approved for comms issue 32 (#57).

image

The inputs at the top need a bit of formatting - we've already done that work in SCISAT though so maybe it would just be a matter of copying that formatting over? Not sure what your preferred approach would be though - however you want to do it.

**Pull request closed without merging**
